downgraded jersey because of java.lang.NoClassDefFoundError: Could not initialize class org.glassfish.jersey.server.internal.JerseyRequestTimeoutHandler